[ENG-47451] Pass region to the Collector Agent
CloudHealth/helm pull request #102
Opened 2023-09-28 07:08 UTC by satyamsinghh

Pass Region to the Agent. If not set, then default value "us-east-1" would be used
**Jira**: https://cloudhealthtech.atlassian.net/browse/ENG-47451

2023-09-28 13:29 UTC, gm-cht commented
@satyamsinghh This is a helm chart for an agent that is installed on a customer's Kubernetes cluster. This should not have `chtRegion` as a parameter at all..

2023-09-28 19:34 UTC, gm-cht commented
> @satyamsinghh This is a helm chart for an agent that is installed on a customer's Kubernetes cluster. This should not have `chtRegion` as a parameter at all.. It communicates at the endpoint `https://containers-api.edge.cloudhealthtech.com`. This is a DNS entry and is not region specific at all.

NVM.. I just saw the other `cp-containers` PR..

2023-09-28 19:48 UTC, gm-cht requested changes
Need to change version in `Chart.yml` to `4.2.0`

2023-09-28 19:48 UTC, gm-cht commented on README.md
> +$ helm install cloudhealth-collector --set apiToken=<Unique Customer API Token>,clusterName=<Cluster Name>,chtRegion=<Cloudhealth Region> cloudhealth/cloudhealth-collector
Since this parameter is optional, I am not sure we need to change the ReadMe. Similar feedback in [`cloudpercept` PR](https://github.com/CloudHealth/cloudpercept/pull/24431).

2023-09-28 19:48 UTC, gm-cht commented on README.md
> +$ helm install cloudhealth-collector --set apiToken=<Unique Customer API Token>,clusterName=<Cluster Name>,chtRegion=<Cloudhealth Region> cloudhealth/cloudhealth-collector
optional. need change?

2023-09-28 19:48 UTC, gm-cht commented on README.md
> +$ helm install cloudhealth-collector -n <target_namespace> --set apiToken=<Unique Customer API Token>,clusterName=<Cluster Name>,chtRegion=<Cloudhealth Region> cloudhealth/cloudhealth-collector
optional. need change?

2023-09-29 13:29 UTC, pjiten commented on charts/cloudhealth-collector/templates/deployment.yaml
> +              value: {{.Values.chtRegion | default "us-east-1" }}
Do we need to set `default` here when we already specified it in `values.yaml` as well.

2023-09-29 16:33 UTC, satyamsinghh commented on charts/cloudhealth-collector/templates/deployment.yaml
> +              value: {{.Values.chtRegion | default "us-east-1" }}
@pjiten in this repository's README, there are other options also provided to install the helm chart.  
The default value provided in the `values.yaml` file will only be used when we will be using that file to install helm chart. However, for other two options this may not be relevant. 
So the options could be,
1. Keep the default at both the places. 
2. or, we can skip setting default value in `values.yaml` file and just keep it here.
2. or, we can make this variable compulsory and remove the default from all the place. 

Please do let me know about your opinion or any other option &, accordingly i can make the change.

2023-09-29 16:39 UTC, satyamsinghh commented on README.md
> +$ helm install cloudhealth-collector --set apiToken=<Unique Customer API Token>,clusterName=<Cluster Name>,chtRegion=<Cloudhealth Region> cloudhealth/cloudhealth-collector
This parameter is kept optional as majority of upcoming deployment would be happening in us-east-1 so default is set to "us-east-1" so that nothing breaks even if this variable is not supplied. 
However, for any other region, this variable requires to be set with appropriate value. Hence, it is required to keep this in the instructions.

The other option could be "**Make this variable compulsory**" for all the regions.

Please do let me know your opinion and accordingly i can make the change to this PR.

2023-09-29 16:40 UTC, satyamsinghh commented on README.md
> +$ helm install cloudhealth-collector --set apiToken=<Unique Customer API Token>,clusterName=<Cluster Name>,chtRegion=<Cloudhealth Region> cloudhealth/cloudhealth-collector
added details in above thread 
https://github.com/CloudHealth/helm/pull/102#discussion_r1341588201

2023-09-29 16:40 UTC, satyamsinghh commented on README.md
> +$ helm install cloudhealth-collector -n <target_namespace> --set apiToken=<Unique Customer API Token>,clusterName=<Cluster Name>,chtRegion=<Cloudhealth Region> cloudhealth/cloudhealth-collector
added details in above thread 
https://github.com/CloudHealth/helm/pull/102#discussion_r1341588201

2023-09-29 20:30 UTC, gm-cht commented on README.md
> +$ helm install cloudhealth-collector --set apiToken=<Unique Customer API Token>,clusterName=<Cluster Name>,chtRegion=<Cloudhealth Region> cloudhealth/cloudhealth-collector
Let me talk to team and make some suggestions. having it in `values.yml` is good enough. Do not need to update the customer facing ReadMe was my opinion.

2023-09-29 20:40 UTC, satyamsinghh commented on README.md
> +$ helm install cloudhealth-collector --set apiToken=<Unique Customer API Token>,clusterName=<Cluster Name>,chtRegion=<Cloudhealth Region> cloudhealth/cloudhealth-collector
Just to add some more points,
we can add only default value (us-east-1 in this case) in the values.yaml. But how do we provide the region when we are deploying in other region lets say `eu-central-1`. That is when it would be required to configure region by the customer.

2023-10-05 06:31 UTC, satyamsinghh commented
> Need to change version in `Chart.yml` to `4.2.0`

@gm-cht Updated chart version to 4.2.0

2023-10-10 16:13 UTC, msahacode approved these changes

2023-10-11 03:42 UTC, gm-cht commented
Added a new commit with a `values.schema.json` that can be used to restrict regions we support. This actually prevents users from installing with an unsupported region.
Will review this with team.

We also need to wait for a new collector image generated from this PR: https://github.com/CloudHealth/cp-containers/pull/1420 and update the image tag in `values.yaml` and update `appVersion` in `Chart.yml` before we can merge this PR..

cc @satyamsinghh

2023-10-11 05:55 UTC, satyamsinghh commented on charts/cloudhealth-collector/values.schema.json
> +            "pattern": "^(us-east-1|us-east-2)$"
@trjaskoviak @msahacode do we also need to include eu-central-1 ?

2023-10-11 13:07 UTC, gm-cht commented on charts/cloudhealth-collector/values.schema.json
> +            "pattern": "^(us-east-1|us-east-2)$"
We can add a new region after we have collection endpoint in that region. We can make it a new version of helm that support EU region.

2023-10-11 15:12 UTC, gm-cht commented on charts/cloudhealth-collector/values.yaml
> -service:
Unused. We do not create a k8s service

2023-10-11 15:40 UTC, gm-cht commented on charts/cloudhealth-collector/templates/deployment.yaml
> +              value: {{.Values.chtRegion | default "us-east-1" }}
it is good to have this default since if a `helm install` command overrides to empty this will still set it to `us-east-1`

2023-10-12 14:56 UTC, pjiten approved these changes

2023-10-20 14:02 UTC, trjaskoviak requested changes

2023-10-20 14:02 UTC, trjaskoviak commented on README.md
> +| `image.tag`                 | CloudHealth Collector image tag                                                                   | `1360`                            |
```suggestion
| `image.tag`                 | CloudHealth Collector image tag                                                                   | `1398`                            |
```

Latest is 1398

2023-10-20 14:08 UTC, trjaskoviak approved these changes

2023-10-20 15:13 UTC, gitHubDjs approved these changes

2023-10-20 15:54 UTC, merged