[SDO-2649] k8s optimizer
CloudHealth/helm pull request #103
Opened 2023-10-16 13:20 UTC by gm-cht

2023-10-20 00:05 UTC, pjiten requested changes

2023-10-20 00:05 UTC, pjiten commented on charts/cloudhealth-collector/templates/secrets.yaml
> +  chapiToken:  {{ .Values.optimizer.chapiToken | b64enc | quote }}
```suggestion
  chapiToken:  {{ .Values.optimizer.chapiKey | b64enc | quote }}
```

2023-10-20 00:05 UTC, pjiten commented on charts/cloudhealth-collector/values.yaml
> +  chapiToken: ""
```suggestion
  chapiKey: ""
```

2023-10-20 00:52 UTC, pjiten commented on charts/cloudhealth-collector/templates/optimizer-agent-cron.yaml
> +            image: "{{ .Values.optimizer.image.repository }}:{{ .Values.optimizer.image.tag | default .Chart.AppVersion }}"
If the keys are case sensitive, should the `AppVersion` be `appVersion`?

2023-10-20 01:00 UTC, pjiten commented on charts/cloudhealth-collector/templates/optimizer-agent-cron.yaml
> +            image: "{{ .Values.optimizer.image.repository }}:{{ .Values.optimizer.image.tag | default .Chart.AppVersion }}"
Nevermind. I got my answer for this exact case. 
https://stackoverflow.com/questions/67714954/are-helm-variables-case-insensitive-the-templates-seem-to-be

2023-10-20 01:00 UTC, pjiten approved these changes

2023-10-20 01:28 UTC, gm-cht commented on charts/cloudhealth-collector/templates/optimizer-agent-cron.yaml
> +            image: "{{ .Values.optimizer.image.repository }}:{{ .Values.optimizer.image.tag | default .Chart.AppVersion }}"
good to know. TIL. to avoid confusion, I might as well change it to lowercase.. `appVersion`

2023-10-20 01:29 UTC, gm-cht commented on charts/cloudhealth-collector/templates/optimizer-agent-cron.yaml
> +            image: "{{ .Values.optimizer.image.repository }}:{{ .Values.optimizer.image.tag | default .Chart.AppVersion }}"
actually it should default to `latest`.

2023-10-20 21:14 UTC, gitHubDjs commented on charts/cloudhealth-collector/NOTES.txt
> +helm install cloudhealth-collector --debug --dry-run --set apiToken=$CHT_API_TOKEN,clusterName=$CHT_CLUSTER_NAME,image.repository=latest-libs-06-13-3,image.pullPolicy=Never --set devArgs="\['upload_k
Did we remove `chtRegion=$CHT_REGION` purposely?

2023-10-20 21:14 UTC, gitHubDjs commented on charts/cloudhealth-collector/templates/optimizer-agent-cron.yaml
> +                value: {{.Values.clusterName | required "A valid clusterName required!" | quote }}
```suggestion
                value: {{.Values.clusterName | required "A valid clusterName is required!" | quote }}
```

2023-10-23 13:30 UTC, gm-cht commented on charts/cloudhealth-collector/NOTES.txt
> +helm install cloudhealth-collector --debug --dry-run --set apiToken=$CHT_API_TOKEN,clusterName=$CHT_CLUSTER_NAME,image.repository=latest-libs-06-13-3,image.pullPolicy=Never --set devArgs="\['upload_k
probably a merge conflict. will fix it.

2023-10-31 21:15 UTC, gitHubDjs requested changes

2023-10-31 21:15 UTC, gitHubDjs commented on README.md
> +To install the chart with the release name `cloudhealth-collector-optimizer`, run the following command:
Plural (there are 2 commands below):
```suggestion
To install the chart with the release name `cloudhealth-collector-optimizer`, run the following commands:
```

2023-10-31 21:15 UTC, gitHubDjs commented on README.md
> +To install the chart with the release name `cloudhealth-collector-optimizer`, run the following command:
Should we say "in the default namespace" or something? E.g., 
```suggestion
To install the chart with the release name `cloudhealth-collector-optimizer` in the default namespace, run the following command:
```

2023-10-31 21:15 UTC, gitHubDjs commented on README.md
> +To install the chart with the release name `cloudhealth-collector-optimizer` in a particular namespace `<target_namespace>`, run the following commands:
Better (since the "unspecified" default namespace is a particular namespace, too, even if it's just the root, right), maybe?
```suggestion
To install the chart with the release name `cloudhealth-collector-optimizer` in a specified namespace `<target_namespace>`, run the following commands:
```

2023-11-01 15:46 UTC, kscherme requested changes

2023-11-01 15:46 UTC, kscherme commented on charts/cloudhealth-collector/Chart.yaml
> +version: 5.5.0-beta
Does this mean that once we merge this in, the "latest" release will be "5.5.0-beta"?  So customers that automatically update their agent, will automatically update to the beta chart. Is that what we want to happen?

2023-11-01 15:46 UTC, kscherme commented on charts/cloudhealth-collector/NOTES.txt
> +helm install cloudhealth-collector --debug --dry-run -n cloudhealth --set clusterName=test-cluster,apiToken=tttyyy cloudhealth/cloudhealth-collector --version 5.0.6-alpha
Do we still need alpha instructions once the beta version is released?

2023-11-01 15:46 UTC, kscherme commented on charts/cloudhealth-collector/templates/deployment.yaml
> +          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
Should we keep this as `.Chart.AppVersion` for the collector agent image?

2023-11-01 16:03 UTC, gitHubDjs approved these changes

2023-11-01 18:02 UTC, gm-cht commented on charts/cloudhealth-collector/Chart.yaml
> +version: 5.5.0-beta
This PR won't be merged until GA. This branch will keep releasing beta versions. 
The only manual step is, every check-in to this branch we need to manually go to Releases and set the release as `pre-release`

2023-11-01 18:02 UTC, gm-cht commented on charts/cloudhealth-collector/NOTES.txt
> +helm install cloudhealth-collector --debug --dry-run -n cloudhealth --set clusterName=test-cluster,apiToken=tttyyy cloudhealth/cloudhealth-collector --version 5.0.6-alpha
good catch.. fixing it.

2023-11-01 18:03 UTC, gm-cht commented on charts/cloudhealth-collector/templates/deployment.yaml
> +          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
`.Chart.AppVersion` is not a valid image tag at all. thus changed it.

2023-11-01 18:19 UTC, kscherme commented on charts/cloudhealth-collector/templates/deployment.yaml
> +          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
good catch :)

2023-11-01 18:19 UTC, kscherme approved these changes

2024-08-07 19:13 UTC, closed without merging