[CHE-202] Add namespace label beta instructions
CloudHealth/helm pull request #33
Opened 2022-04-06 17:30 UTC by kscherme

Adding instructions for deploying the agent with the public beta namespace instructions.

2022-04-06 18:00 UTC, gm-cht approved these changes

2022-04-07 03:55 UTC, gitHubDjs requested changes

2022-04-07 03:55 UTC, gitHubDjs commented on README.md
> +$ helm install cloudhealth-collector --set apiToken=$CHT_API_TOKEN,clusterName=$CHT_CLUSTER_NAME --set devArgs="\['upload_k8s_state_v2'\,'--verbose'\]" cloudhealth/cloudhealth-collector
This command has references to two env variables that are not defined in this readme (`$CHT_API_TOKEN` and `$CHT_CLUSTER_NAME`); in the command on line 32 we expressed those as `--set apiToken=<Unique Customer API Token>,clusterName=<Cluster Name>`

2022-04-07 03:55 UTC, gitHubDjs commented on README.md
>  To install the chart with the release name `cloudhealth-collector` in a particular namespace `<target_namespace>`, run the following command:
What if you want to install it in a particular namespace **_and_** also enable the collection of namespace resources (currently in public BETA)? Does this need to be clarified?

2022-04-07 03:55 UTC, gitHubDjs commented on README.md
>  To install the chart with the release name `cloudhealth-collector` in a particular namespace `<target_namespace>`, run the following command:
Also, this says "`...run the following command`", but there are _two_ commands following, not one.

2022-04-07 03:55 UTC, gitHubDjs commented on README.md
> +`BETA` To allow the collector agent to also collect namespace resources, run the above command with the following `devArgs` set:
I think this would be a little clearer, since there are _two_ commands above: 
```suggestion
`BETA` To allow the collector agent to also collect namespace resources, run the above `install` command with the following `devArgs` set:
```

2022-04-07 03:55 UTC, gitHubDjs commented on README.md
> +`BETA` To allow the collector agent to also collect namespace resources, run the above command with the following `devArgs` set:
Also, for a cluster that wasn't already running the collector agent, you don't want them to run the `install` twice (i.e., once as in the example on line 32, and then a second time to enable the beta feature), right? That might need to be clarified.

2022-04-07 13:12 UTC, kscherme commented on README.md
> +`BETA` To allow the collector agent to also collect namespace resources, run the above command with the following `devArgs` set:
I tried re-wording to clarify the instructions.  Does this seem better?

2022-04-07 14:25 UTC, gitHubDjs commented on README.md
> +`BETA` To allow the collector agent to also collect namespace resources, run the above command with the following `devArgs` set:
One more thing: Does `devArgs` need to be added to the table in the Parameters section now? Here: 

- https://github.com/CloudHealth/helm/blob/0b899934bea4a2c89c50d0ab9ed1572b89b55af7/README.md#parameters

2022-04-07 14:31 UTC, gitHubDjs reviewed
See latest comments

2022-04-07 14:38 UTC, gitHubDjs approved these changes

2022-04-07 17:49 UTC, bswetalina approved these changes

2022-04-07 17:50 UTC, merged