Changes to address 2 open issues.
CloudHealth/helm pull request #51
Opened 2022-06-10 21:27 UTC by gm-cht

https://github.com/CloudHealth/helm/issues/44
https://github.com/CloudHealth/helm/issues/46

2022-06-16 14:24 UTC, trjaskoviak requested changes

2022-06-16 14:24 UTC, trjaskoviak commented on README.md
> +| `customEnvVars`                          | Extra envrionment variable to add to pod created by this chart                                                            | `[]`            |
```suggestion
| `customEnvVars`                          | Extra environment variable to add to pod created by this chart                                                            | `[]`            |
```

2022-06-16 14:24 UTC, trjaskoviak commented on README.md
> +| `customEnvVars`                          | Extra envrionment variable to add to pod created by this chart                                                            | `[]`            |
We might also mention that we need a "name" and "value" for each item in the array.

2022-06-16 20:09 UTC, fnannizzi approved these changes

2022-06-17 14:12 UTC, gitHubDjs approved these changes

2022-06-17 14:22 UTC, merged