Update docs for new docker image
CloudHealth/helm pull request #54
Opened 2022-06-16 20:07 UTC by gm-cht

2022-06-16 20:10 UTC, trjaskoviak approved these changes

2022-06-16 20:16 UTC, kscherme approved these changes

2022-06-17 15:57 UTC, gitHubDjs requested changes

2022-06-17 15:57 UTC, gitHubDjs commented on cloudhealth-collector-image-docs/CHANGELOG.md
> +## [1180] - 2022-06-16
```suggestion
## [1180] - 2022-06-17
```

2022-06-17 15:57 UTC, gitHubDjs approved these changes

2022-06-17 15:58 UTC, merged