[CHE-264]: Update CHANGELOG for liveness check
CloudHealth/helm pull request #63
Opened 2022-08-16 15:53 UTC by bswetalina

2022-08-16 19:26 UTC, pjiten approved these changes

2022-08-16 19:58 UTC, trjaskoviak approved these changes

2022-08-17 14:34 UTC, gitHubDjs requested changes

2022-08-17 14:34 UTC, gitHubDjs commented on cloudhealth-collector-image-docs/CHANGELOG.md
> +  * Added a new file liveness.txt in collector pod /tmp folder.Every time collection is performed for any resource, the
Whitespace:
```suggestion
  * Added a new file liveness.txt in collector pod /tmp folder. Every time collection is performed for any resource, the
```

2022-08-17 15:34 UTC, gitHubDjs approved these changes

2022-08-17 17:33 UTC, merged