CHE-318: Update chart and appVersion as per the new versioning scheme
CloudHealth/helm pull request #64
Opened 2022-08-25 16:38 UTC by pjiten

Test plan:
Had minikube deployed locally. 
Successfully deployed multiple collector images 1203 and 1191 locally using these local helm chart changes.

2022-08-25 18:34 UTC, gm-cht commented
@pjiten will be good to have some screenshots on command you ran and the version you checked.

2022-08-25 20:57 UTC, gitHubDjs commented on cloudhealth-collector/values.yaml
>    # Overrides the image tag whose default is the chart appVersion.
Doesn't the comment need to be revised now?

2022-08-25 22:56 UTC, wxia20 commented on cloudhealth-collector/values.yaml
> +  tag: ""
I'm sure it tested and works. Just wondering which is better? `tag: ""` or remove this line completely?

2022-08-26 00:49 UTC, pjiten commented on cloudhealth-collector/values.yaml
> +  tag: ""
I read in multiple forums that most chart users expect 'image.tag' to be present in values.yaml. I also remember @gm-cht mentioning that Helm allows users to overwrite  identifier on command line only if that identifier is already defined in the values.yaml.

2022-08-26 03:55 UTC, pjiten commented on cloudhealth-collector/values.yaml
> +  tag: ""
I was able to repeat the same tests as above after removing this line completely. I guess we could remove it.

2022-08-26 10:57 UTC, wxia20 commented on cloudhealth-collector/values.yaml
> +  tag: ""
Yeah the value overwrite doesn't require the value to be present in values.yaml. As I mentioned, both works, It's up to you.

2022-08-26 14:01 UTC, pjiten commented on cloudhealth-collector/values.yaml
> +  tag: ""
Removed this field and comments completely. Updated readme.md

2022-08-26 14:04 UTC, kscherme requested changes
Looks good, just small question about the PullPolicy.  Also, I was just thinking about the manual deployment route - do we need to change that yaml as well?

2022-08-26 14:04 UTC, kscherme commented on cloudhealth-collector/values.yaml
>    pullPolicy: Always
Did we want to change this to `IfNotPresent`?

2022-08-26 14:56 UTC, wxia20 commented on cloudhealth-collector/values.yaml
>    pullPolicy: Always
> Did we want to change this to `IfNotPresent`?

+1

2022-08-26 16:48 UTC, pjiten commented on cloudhealth-collector/values.yaml
>    pullPolicy: Always
![image](https://user-images.githubusercontent.com/89090133/186951805-e8217742-8b7e-48f9-89e0-842dbad0ec4a.png)
After reading this, I am still not quite sure what's the difference. But what I understood so far is this:
IfNotPresent: Kubelet just looks at the image name and decides if it already exists locally or need to pull that image from the registry
Always: Kubelet always queries the registry to resolve image name to its digest. Then Kubelet uses that digest to decide if it is already cached locally. If it is not cached yet, kubelet pulls that image from the registry. 

If my understanding is right, 'Always' is still very optimized since it do not ALWAYS pull the image. A good benefit of this behavior is in dev env where someone likes to make code changes progressively and test each version of it without actually bumping up the image version. One may publish the updated container image without bumping up its version, yet kubelet will always update the image in container every time because of their different digests

2022-08-26 17:57 UTC, wxia20 commented on cloudhealth-collector/values.yaml
>    pullPolicy: Always
`IfNotPresent` It's the default k8s image deployment policy, we could simple remove this line. 

As @pjiten mentioned, 'Always' force k8s to always make calls to registry at deployment time at least to pull the digest. This is unnecessary as we'll always bump up the image version. The impact of specifying 'Always' policy is bigger nowaday since [`DockerHub Download rate limit`](https://docs.docker.com/docker-hub/download-rate-limit/). 

For local development, if we do not want to bump up the image version, then we can alway overwrite in helm using ```--set image.pullPolicy:Always```.

2022-08-26 18:01 UTC, kscherme commented on cloudhealth-collector/values.yaml
>    pullPolicy: Always
Looking at helm best practices (https://helm.sh/docs/chart_best_practices/pods/), it doesn't say not to use `Always`, but `IfNotPresent` is default.  `Always` says it will always query the container image registry every time the kubelet launches a container, so that could be unneeded.  It probably does not matter too much, but I am thinking it is easier to keep it consistent with other Vmware helm charts? https://github.com/wavefrontHQ/helm

2022-08-26 18:22 UTC, pjiten commented on cloudhealth-collector/values.yaml
>    pullPolicy: Always
done

2022-08-26 18:29 UTC, glichtenISP reviewed
I would highly suggest reviewing the documentation around [semantic versioning](https://semver.org/). By using it correctly, it will convey quite a bit of useful info to the consumers of the chart at just a glance, but if used incorrectly can cause unexpected outages.

2022-08-26 18:29 UTC, glichtenISP commented on cloudhealth-collector/Chart.yaml
> +appVersion: "1191"
I would highly suggest retaining semantic versioning for the `appVersion`, and updating `image.tag` with the appropriate image tag. When using semantic versioning correctly, it tells consumers of the chart, what sorts of changes to expect from within the application.
Eg:
- When going from 3.0.0 -> 3.0.1 --- I can expect nothing will break in it's current operation. This is a safe dependency update, & there are simply bug fixes & other minor patches to the application. I probably don't need to review the changelog, unless there's security or bug fix I'm expecting.
- When going from 3.0.0 -> 3.1.0 --- I can expect nothing will break in it's current operation. There have been feature additions and possibly non-breaking bug fixes & patches to the application. I should review the changelog to see what features have been added.
- When going from 3.0.0 -> 4.0.0 --- I can expect there have been possible breaking changes to the way the application functions (Removed API's, argument changes/removals, etc). I need to review the release notes fully to understand if any of the changes made to the application require changes in the way that I use it, and update my implementation of it accordingly.

2022-08-26 18:29 UTC, glichtenISP commented on cloudhealth-collector/Chart.yaml
> +version: 3.0.0
The changes being made to the chart really don't constitute a major version change from what I'm seeing here. There's no breaking changes taking place here that would require me to perform a `helm uninstall` + `helm install` rather than just a `helm upgrade`. With semantic versioning of the chart, I'd expect similar to the following:
- When going from 2.0.1 -> 2.0.2 --- Minor change to the chart or it's values, like revving the `image.tag` for patch or minor version updates to the `appVersion`.
- When going from 2.1.0 -> 2.1.0 --- Refactoring or adding additional functionality to the chart. Like adding an optional configMap or Service enabled via a new value. The `appVersion` would only change here if there were also changes to the application code.
- When going from 2.0.1 -> 3.0.0 --- Major and/or possibly breaking changes to the chart or application. This could be something like changing the deployment labels & selectors, or taking a major version update on a dependency chart installed by default. Also major version changes to the `appVersion` would also mean a major version change to the chart.

2022-08-29 15:36 UTC, wxia20 approved these changes

2022-08-29 15:39 UTC, pjiten commented on cloudhealth-collector/Chart.yaml
> +appVersion: "1191"
Thank you for your review comments. This makes total sense. I have made suggested changes. We also have a ticket in pipeline to implement proper SemVer versioning for image.tag and appVersion fields that will be based off  jenkins build numbers.

2022-08-29 16:46 UTC, kscherme requested changes

2022-08-29 16:46 UTC, kscherme commented on cloudhealth-collector/values.yaml
> +  tag: "1203"
I think pullPolicy was left out here

2022-08-29 16:50 UTC, pjiten commented on cloudhealth-collector/values.yaml
> +  tag: "1203"
That was intentional. As per Wei's previous comment that we can remove it since default pullPolicy of k8s is already 'IfNotPresent'.

2022-08-29 17:50 UTC, kscherme approved these changes

2022-08-29 18:17 UTC, pjiten commented on index.yaml
> +    digest: d50a0a5bf076eff665d1a4d7bfa13034bdad8932f345f976572161b6d9167ad3
@gm-cht @kscherme. I am not sure why the digest of an existing version is updated in this line. I don't see it happened in this older PR. https://github.com/CloudHealth/helm/pull/59/files#diff-08c65c1b5ef8384ef0200558777c52f4110afcbbacc880ac5375d555ca97ee3e

2022-08-30 14:18 UTC, gm-cht approved these changes

2022-08-30 15:44 UTC, merged