Add dnsConfig in values.yaml
CloudHealth/helm pull request #75
Opened 2022-10-19 04:10 UTC by bcdady

Address DNS issues in #73

2022-10-28 14:29 UTC, gm-cht requested changes

2022-10-28 14:29 UTC, gm-cht commented on cloudhealth-collector/values.yaml
> +dnsConfig:
The default has to be an empty `{}`. The `deployment.yaml` file has to change to include this option parameter.

2022-10-31 03:54 UTC, bcdady commented on cloudhealth-collector/values.yaml
> +dnsConfig:
I'll look into adding this soon.

2022-11-08 16:16 UTC, bcdady commented on cloudhealth-collector/values.yaml
> +dnsConfig:
Hi @gm-cht Could you re-review and let me know if you see anything else that needs follow-up here?

2022-11-08 17:54 UTC, pjiten commented on cloudhealth-collector-image-docs/CHANGELOG.md
Everything looks good to me. I am just curious if changes in this file CHANGELOG.md are unintentional, caused by an editor or something.

2022-11-08 18:36 UTC, gm-cht approved these changes

2022-11-08 18:37 UTC, gm-cht commented on cloudhealth-collector/values.yaml
> +dnsConfig:
@bcdady looks good to me. let us run some tests our end and will merge this.

2022-11-09 04:16 UTC, bcdady commented on cloudhealth-collector-image-docs/CHANGELOG.md
Thanks @pjiten. Yes the markdown edits were to make markdownlint happy.

2022-11-09 14:47 UTC, pjiten commented on cloudhealth-collector-image-docs/CHANGELOG.md
Awesome. I am performing some usual testing in local sandbox. I will approve as soon as I finish it today.

2022-11-10 17:36 UTC, pjiten approved these changes

2022-11-10 18:10 UTC, wxia20 approved these changes

2022-11-10 20:46 UTC, merged