[SDO-2545]: Add helm changes to use the new Collection API and update changelog
CloudHealth/helm pull request #97
Opened 2023-07-06 14:50 UTC by bswetalina

… changelog.

2023-07-07 12:20 UTC, kscherme requested changes
Need to increment the versions in `chart.yaml`, otherwise all set!

2023-07-07 12:20 UTC, kscherme commented on cloudhealth-collector-image-docs/CHANGELOG.md
> +* The collector docker image now supports collecting the UID and kubernetes agent version.
Since this is a larger change, can we get Pavan's feedback on this to make sure there isn't anything that he would like to add

2023-07-07 17:32 UTC, bswetalina commented on cloudhealth-collector-image-docs/CHANGELOG.md
> +* The collector docker image now supports collecting the UID and kubernetes agent version.
@pkchavva  has confirmed that this looks good :)

2023-07-10 13:09 UTC, kscherme requested changes

2023-07-10 13:09 UTC, kscherme commented on charts/cloudhealth-collector/Chart.yaml
> +appVersion: "4.0.1"
Since this is adding significant functionality to the app, should the `appVersion` be 4.1.0?  Or even 5.0.0?

2023-07-10 18:24 UTC, bswetalina commented on charts/cloudhealth-collector/Chart.yaml
> +appVersion: "4.0.1"
I was under the impression the app Version is upped a version when a big helm change is added and version tracks any collector related changes, as this includes a big collector change I upped the version.

2023-07-10 18:36 UTC, kscherme approved these changes

2023-07-10 19:06 UTC, anjal4CH approved these changes

2023-07-12 21:09 UTC, trjaskoviak approved these changes

2023-07-19 17:36 UTC, merged